name: flutter_cupertino_datetime_picker
description: Fork from flutter_cupertino_date_picker https://github.com/wuzhendev/flutter-cupertino-date-picker, but year, month, day seperate
version: 2.0.1
homepage: https://github.com/ykrank/flutter_cupertino_datetime_picker

dependencies:
  flutter:
    sdk: flutter

flutter:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=0.4.1"
